<?php

namespace Tests\Unit\Http\Models;

use App\Http\Models\User;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Tests\TestCase;

class UserTest extends TestCase
{
    protected $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unset($this->user);
    }

    public function test_fillable()
    {
        $this->assertEquals([
            'name',
            'email',
            'phone_number',
            'username',
            'password',
            'role_id',
            'active',
        ], $this->user->getFillable());
    }

    public function test_belongsTo_relation()
    {
        $relation = $this->user->role();

        $this->assertInstanceOf(BelongsTo::class, $relation);
        $this->assertEquals('role_id', $relation->getForeignKeyName());
    }

    public function test_hasMany_relation()
    {
        $relation = $this->user->comments();

        $this->assertInstanceOf(HasMany::class, $relation);
        $this->assertEquals('user_id', $relation->getForeignKeyName());
    }

    public function test_belongsToMany_relation()
    {
        $relation = $this->user->likes();

        $this->assertInstanceOf(BelongsToMany::class, $relation);
        $this->assertEquals('news_id', $relation->getRelatedPivotKeyName());
    }
}
