<?php

namespace Tests\Unit\Http\Controllers;

use App\Http\Controllers\AdminController;
use App\Http\Models\Category;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\ParameterBag;
use Tests\TestCase;

class AdminControllerTest extends TestCase
{
    protected $controller;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->controller = new AdminController();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unset($this->controller);
    }

    public function test_indexNews()
    {
        $view = $this->controller->indexNews();

        $this->assertEquals('admin.news', $view->getName());
        $this->assertArrayHasKey('listNews', $view->getData());
    }

    public function test_showNews()
    {
        $view = $this->controller->showNews('1058');

        $this->assertEquals('admin.newsdetail', $view->getName());
        $this->assertArrayHasKey('news', $view->getData());
    }

    public function test_showNews_fail()
    {
        $response = $this->controller->showNews('1');

        $this->assertInstanceOf(RedirectResponse::class, $response);
        $this->assertEquals(route('admin.news.index'), $response->headers->get('Location'));
    }

    public function test_searchNews()
    {
        $data = [
            'keyWord' => 'ad',
        ];
        $request = new Request();
        $request->headers->set('content-type', 'application/json');
        $request->setJson(new ParameterBag($data));

        $view = $this->controller->searchNews($request);

        $this->assertEquals('admin.news', $view->getName());
        $this->assertArrayHasKey('listNews', $view->getData());
        $this->assertArrayHasKey('keyWord', $view->getData());
    }

    public function test_indexCategories()
    {
        $view = $this->controller->indexCategories();

        $this->assertEquals('admin.categories', $view->getName());
        $this->assertArrayHasKey('rootCategories', $view->getData());
    }

    public function test_category()
    {
        $view = $this->controller->category(3);

        $this->assertEquals('admin.news', $view->getName());
        $this->assertArrayHasKey('curCategory', $view->getData());
        $this->assertArrayHasKey('listNews', $view->getData());
    }

    public function test_category_fail()
    {
        $response = $this->controller->category(100);

        $this->assertInstanceOf(RedirectResponse::class, $response);
        $this->assertEquals(route('admin.news.index'), $response->headers->get('Location'));
    }
}
